In [43]:
import pandas as pd

In [59]:
df = pd.read_csv("C:/Users/TANNERU/Downloads/fake-news/train.csv")

In [60]:
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[20800 rows x 5 columns]

In [61]:
len(df)

20800

In [62]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [63]:
df = df.dropna()

In [64]:
len(df)

18285

In [65]:
df.head(10)

id                                              title  \
0    0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1    1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2    2                  Why the Truth Might Get You Fired   
3    3  15 Civilians Killed In Single US Airstrike Hav...   
4    4  Iranian woman jailed for fictional unpublished...   
5    5  Jackie Mason: Hollywood Would Love Trump if He...   
7    7  Benoît Hamon Wins French Socialist Party’s Pre...   
9    9  A Back-Channel Plan for Ukraine and Russia, Co...   
10  10  Obama’s Organizing for Action Partners with So...   
11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   

                          author  \
0                  Darrell Lucus   
1                Daniel J. Flynn   
2             Consortiumnews.com   
3                Jessica Purkiss   
4                 Howard Portnoy   
5                Daniel Nussbaum   
7                Alissa J. Rubin   
9   Megan Twohey and Scott Shane   
10                   Aaron Klein   
11               Chris Tomlinson   

                                                 text  label  
0   House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1   Ever get the feeling your life circles the rou...      0  
2   Why the Truth Might Get You Fired October 29, ...      1  
3   Videos 15 Civilians Killed In Single US Airstr...      1  
4   Print \nAn Iranian woman has been sentenced to...      1  
5   In these trying times, Jackie Mason is the Voi...      0  
7   PARIS  —   France chose an idealistic, traditi...      0  
9   A week before Michael T. Flynn resigned as nat...      0  
10  Organizing for Action, the activist group that...      0  
11  The BBC produced spoof on the “Real Housewives...      0

In [66]:
df.shape

(18285, 5)

In [67]:
X = df['title']
Y = df['label']

In [68]:
print(X.shape)
print(Y.shape)

(18285,)
(18285,)


In [69]:
X

0        House Dem Aide: We Didn’t Even See Comey’s Let...
1        FLYNN: Hillary Clinton, Big Woman on Campus - ...
2                        Why the Truth Might Get You Fired
3        15 Civilians Killed In Single US Airstrike Hav...
4        Iranian woman jailed for fictional unpublished...
                               ...                        
20795    Rapper T.I.: Trump a ’Poster Child For White S...
20796    N.F.L. Playoffs: Schedule, Matchups and Odds -...
20797    Macy’s Is Said to Receive Takeover Approach by...
20798    NATO, Russia To Hold Parallel Exercises In Bal...
20799                            What Keeps the F-35 Alive
Name: title, Length: 18285, dtype: object

In [70]:
X = X.reset_index()
X = X.drop(['index'],axis = 1)

In [71]:
X.tail()

title
18280  Rapper T.I.: Trump a ’Poster Child For White S...
18281  N.F.L. Playoffs: Schedule, Matchups and Odds -...
18282  Macy’s Is Said to Receive Takeover Approach by...
18283  NATO, Russia To Hold Parallel Exercises In Bal...
18284                          What Keeps the F-35 Alive

In [72]:
Y = Y.reset_index()
Y = Y.drop(['index'],axis = 1)

In [73]:
Y.tail()

label
18280      0
18281      0
18282      0
18283      1
18284      1

# Data cleaning

In [74]:
import re
import numpy as np
import nltk
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [75]:
ps = PorterStemmer()
lemma = WordNetLemmatizer()
corpus = []

In [76]:
for i in range(0,len(X)):
    review = re.sub('[^a-z]',' ',X['title'][i])
    review = review.lower()
    review = review.split()
    #stemming
    #review = [ps.stem(word) for word in review if word not in stopwords.words('english')]
    #lemmatising
    review = [lemma.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)
    

In [77]:
corpus

['ouse em ide e idn ven ee omey etter ntil ason haffetz weeted',
 'illary linton ig oman ampus reitbart',
 'hy ruth ight et ou ired',
 'ivilians illed n ingle irstrike ave een dentified',
 'ranian woman jailed fictional unpublished story woman stoned death adultery',
 'ackie ason ollywood ould ove rump e ombed orth orea ack rans athrooms xclusive ideo reitbart',
 'eno amon in rench ocialist arty residential omination ew ork imes',
 'ack hannel lan kraine ussia ourtesy rump ssociates ew ork imes',
 'bama rganizing ction artners oros inked ndivisible isrupt rump genda',
 'omedy ketch eal ousewives au utrage',
 'ussian esearchers iscover ecret azi ilitary ase reasure unter rctic hotos',
 'fficials ee ink etween rump ussia',
 'e e aid overnment roll n ocial edia log orums nd ebsites',
 'n ajor eague occer rgentines ind ome uccess ew ork imes',
 'ell argo hief bruptly teps ew ork imes',
 'nonymous onor ays illion elease veryone rrested akota ccess ipeline',
 'loses n n illary',
 'huck odd u

In [78]:
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers.embeddings import Embedding

In [79]:
voc_size=5000

In [80]:
#performing on hot representation

onehot_repr=[one_hot(words,voc_size)for words in corpus] 

In [81]:
onehot_repr[20]

[1381, 2265, 1046, 2190, 2189, 4340, 1530, 1944, 4869, 953, 4797, 4975]

In [82]:
len(onehot_repr[700])

7

In [83]:
#specifying a sentence length so that every sentence in the corpus will be of same length

sent_length=25

#using padding for creating equal length for every sentences


embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[   0    0    0 ... 1501 4625 2351]
 [   0    0    0 ... 1523 3302  604]
 [   0    0    0 ... 1377  909 2365]
 ...
 [   0    0    0 ...  953 4797 4975]
 [   0    0    0 ... 4086  168  813]
 [   0    0    0 ... 2014   15 1995]]


# Creating model


In [84]:
embedding_vector_features=40

In [86]:
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(200))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [87]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 25, 40)            200000    
_________________________________________________________________
dropout_3 (Dropout)          (None, 25, 40)            0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 200)               192800    
_________________________________________________________________
dropout_4 (Dropout)          (None, 200)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 201       
Total params: 393,001
Trainable params: 393,001
Non-trainable params: 0
_________________________________________________________________


In [89]:
X_final=np.array(embedded_docs)
y_final=np.array(Y)

In [91]:
print(X_final.shape)
print(y_final.shape)

(18285, 25)
(18285, 1)


In [92]:
#splitting the data for training and testing the model

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.20, random_state=42)

In [94]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(14628, 25)
(3657, 25)
(14628, 1)
(3657, 1)


In [95]:
cl = model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=20,batch_size=64)

Train on 14628 samples, validate on 3657 samples
Epoch 1/20
14628/14628 [==============================] - 15s 1ms/step - loss: 0.2972 - acc: 0.8685 - val_loss: 0.2035 - val_acc: 0.9133
Epoch 2/20
14628/14628 [==============================] - 13s 895us/step - loss: 0.1348 - acc: 0.9476 - val_loss: 0.2226 - val_acc: 0.9177
Epoch 3/20
14628/14628 [==============================] - 13s 887us/step - loss: 0.1014 - acc: 0.9630 - val_loss: 0.2341 - val_acc: 0.9185
Epoch 4/20
14628/14628 [==============================] - 13s 891us/step - loss: 0.0721 - acc: 0.9741 - val_loss: 0.2479 - val_acc: 0.9117
Epoch 5/20
14628/14628 [==============================] - 14s 968us/step - loss: 0.0540 - acc: 0.9813 - val_loss: 0.2788 - val_acc: 0.9054
Epoch 6/20
14628/14628 [==============================] - 14s 955us/step - loss: 0.0453 - acc: 0.9857 - val_loss: 0.3034 - val_acc: 0.9068
Epoch 7/20
14628/14628 [==============================] - 14s 949us/step - loss: 0.0295 - acc: 0.9902 - val_loss: 0.385

# Test Dataset

In [128]:
test = pd.read_csv("C:/Users/TANNERU/Downloads/fake-news/test.csv")

In [129]:
test

id                                              title  \
0     20800  Specter of Trump Loosens Tongues, if Not Purse...   
1     20801  Russian warships ready to strike terrorists ne...   
2     20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3     20803  Tim Tebow Will Attempt Another Comeback, This ...   
4     20804                    Keiser Report: Meme Wars (E995)   
...     ...                                                ...   
5195  25995  The Bangladeshi Traffic Jam That Never Ends - ...   
5196  25996  John Kasich Signs One Abortion Bill in Ohio bu...   
5197  25997  California Today: What, Exactly, Is in Your Su...   
5198  25998  300 US Marines To Be Deployed To Russian Borde...   
5199  25999  Awkward Sex, Onscreen and Off - The New York T...   

                       author  \
0            David Streitfeld   
1                         NaN   
2               Common Dreams   
3               Daniel Victor   
4     Truth Broadcast Network   
...                       ...   
5195               Jody Rosen   
5196      Sheryl Gay Stolberg   
5197             Mike McPhate   
5198                      NaN   
5199              Teddy Wayne   

                                                   text  
0     PALO ALTO, Calif.  —   After years of scorning...  
1     Russian warships ready to strike terrorists ne...  
2     Videos #NoDAPL: Native American Leaders Vow to...  
3     If at first you don’t succeed, try a different...  
4     42 mins ago 1 Views 0 Comments 0 Likes 'For th...  
...                                                 ...  
5195  Of all the dysfunctions that plague the world’...  
5196  WASHINGTON  —   Gov. John Kasich of Ohio on Tu...  
5197  Good morning. (Want to get California Today by...  
5198  « Previous - Next » 300 US Marines To Be Deplo...  
5199  Perhaps you’ve seen the new TV series whose pi...  

[5200 rows x 4 columns]

In [130]:
test.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1  20801  Russian warships ready to strike terrorists ne...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1                      NaN  Russian warships ready to strike terrorists ne...  
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
3            Daniel Victor  If at first you don’t succeed, try a different...  
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [131]:
#null values in the test dataset

test.isnull().sum()

id          0
title     122
author    503
text        7
dtype: int64

In [132]:
#using the title column only as we did in the train dataset

test=test.drop(['text','id','author'],axis=1)

In [133]:
test.head()

title
0  Specter of Trump Loosens Tongues, if Not Purse...
1  Russian warships ready to strike terrorists ne...
2  #NoDAPL: Native American Leaders Vow to Stay A...
3  Tim Tebow Will Attempt Another Comeback, This ...
4                    Keiser Report: Meme Wars (E995)

In [134]:
test.isnull().sum()

title    122
dtype: int64

In [135]:
test = test.dropna()

In [136]:
test.isnull().sum()

title    0
dtype: int64

In [137]:
test

title
0     Specter of Trump Loosens Tongues, if Not Purse...
1     Russian warships ready to strike terrorists ne...
2     #NoDAPL: Native American Leaders Vow to Stay A...
3     Tim Tebow Will Attempt Another Comeback, This ...
4                       Keiser Report: Meme Wars (E995)
...                                                 ...
5195  The Bangladeshi Traffic Jam That Never Ends - ...
5196  John Kasich Signs One Abortion Bill in Ohio bu...
5197  California Today: What, Exactly, Is in Your Su...
5198  300 US Marines To Be Deployed To Russian Borde...
5199  Awkward Sex, Onscreen and Off - The New York T...

[5078 rows x 1 columns]

In [138]:
test = test.reset_index()
test = test.drop(['index'],axis = 1)

In [139]:
test

title
0     Specter of Trump Loosens Tongues, if Not Purse...
1     Russian warships ready to strike terrorists ne...
2     #NoDAPL: Native American Leaders Vow to Stay A...
3     Tim Tebow Will Attempt Another Comeback, This ...
4                       Keiser Report: Meme Wars (E995)
...                                                 ...
5073  The Bangladeshi Traffic Jam That Never Ends - ...
5074  John Kasich Signs One Abortion Bill in Ohio bu...
5075  California Today: What, Exactly, Is in Your Su...
5076  300 US Marines To Be Deployed To Russian Borde...
5077  Awkward Sex, Onscreen and Off - The New York T...

[5078 rows x 1 columns]

In [140]:
#creating corpus for the test dataset exactly the same as we created for the training dataset

corpus_test = []
for i in range(0, len(test)):
    review = re.sub('[^a-zA-Z]', ' ',test['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus_test.append(review)

In [141]:
corpus_test

['specter trump loosen tongu purs string silicon valley new york time',
 'russian warship readi strike terrorist near aleppo',
 'nodapl nativ american leader vow stay winter file lawsuit polic',
 'tim tebow attempt anoth comeback time basebal new york time',
 'keiser report meme war e',
 'trump usa antiqu hero clinton next presid',
 'pelosi call fbi investig find russian donald trump breitbart',
 'weekli featur profil randi shannon',
 'urban popul boom make climat chang wors',
 'u gener admir endors trump command chief',
 'work class hero john brennon',
 'rise mandatori vaccin mean end medic freedom',
 'communist terror small busi',
 'comput programm come forward admit paid rig vote booth trump right usa newsflash',
 'thiev take chunk chang pound berlin museum new york time',
 'new england patriot owner still sore n f l payback sight new york time',
 'colleg republican yaf sue berkeley ann coulter event breitbart',
 'trump melt accus us postal servic steal elect clinton',
 'visit madag

In [158]:
#creating one hot representation for the test corpus

onehot_repr_test=[one_hot(words,voc_size)for words in corpus_test]

In [159]:
onehot_repr_test

[[926, 2032, 4223, 303, 2956, 3247, 2090, 2266, 2126, 3042, 398],
 [871, 3684, 1454, 2088, 4260, 3441, 3178],
 [2532, 2149, 3572, 4006, 2369, 4908, 4188, 724, 980, 1352],
 [3368, 2389, 3756, 258, 2549, 398, 4259, 2126, 3042, 398],
 [2069, 2135, 1905, 1186, 2620],
 [2032, 3264, 569, 1142, 4388, 3676, 1161],
 [2726, 3789, 3638, 3725, 1250, 871, 2389, 2032, 741],
 [2190, 2545, 4384, 552, 1343],
 [1069, 4248, 1407, 937, 1219, 832, 4312],
 [4819, 3822, 1401, 4427, 2032, 940, 1221],
 [1326, 790, 1142, 4321, 4971],
 [4949, 2079, 4896, 1943, 682, 3818, 4569],
 [1119, 1456, 476, 4275],
 [1945, 4070, 91, 2482, 463, 3461, 980, 3376, 2742, 2032, 120, 3264, 3467],
 [2213, 3076, 3757, 832, 2030, 750, 1632, 2126, 3042, 398],
 [2126,
  2389,
  705,
  986,
  3013,
  4848,
  168,
  287,
  4871,
  4367,
  4279,
  2126,
  3042,
  398],
 [2090, 3327, 129, 1839, 18, 4412, 972, 876, 741],
 [2032, 2861, 918, 3265, 1689, 523, 2768, 2943, 4388],
 [2238, 3727, 2044, 2565, 3908, 4939, 1230, 1726, 2126, 3042, 398]

In [160]:
onehot_repr_test[99]

[2413, 494, 4259, 2779, 1168, 4059, 2126, 3042, 398]

In [161]:
len(onehot_repr_test)

5078

In [162]:
#padding for the test dataset
sent_length=25

embedded_docs_test=pad_sequences(onehot_repr_test,padding='pre',maxlen=sent_length)
print(embedded_docs_test)

[[   0    0    0 ... 2126 3042  398]
 [   0    0    0 ... 4260 3441 3178]
 [   0    0    0 ...  724  980 1352]
 ...
 [   0    0    0 ... 2126 3042  398]
 [   0    0    0 ...  871 3022  530]
 [   0    0    0 ... 2126 3042  398]]


In [164]:
X_test1=np.array(embedded_docs_test)

In [165]:
#making predictions for the test dataset

predict = model.predict_classes(X_test1)


In [166]:
predict

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])