In [2]:
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [3]:
#prepare Sequence
length = 5

In [4]:
seq = np.array([i/float(length) for i in range(length)])

In [5]:
seq

array([0. , 0.2, 0.4, 0.6, 0.8])

In [7]:
X = seq.reshape(1,length,1)
Y = seq.reshape(1,length)

In [8]:
X

array([[[0. ],
        [0.2],
        [0.4],
        [0.6],
        [0.8]]])

In [9]:
Y

array([[0. , 0.2, 0.4, 0.6, 0.8]])

In [10]:
print(X.shape)
print(Y.shape)

(1, 5, 1)
(1, 5)


In [11]:
n_neurons = length
n_batch = 1
epochs = 500

# Buliding model

In [13]:
model = Sequential()
model.add(LSTM(n_neurons,input_shape = (length,1)))
model.add(Dense(length))#5
model.compile(optimizer = 'adam',loss = 'mean_squared_error')


In [14]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 5)                 140       
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 30        
Total params: 170
Trainable params: 170
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.fit(X,Y,epochs = epochs,batch_size = n_batch)

Epoch 1/500
1/1 [==============================] - 0s 4ms/step - loss: 9.9144e-12
Epoch 2/500
1/1 [==============================] - 0s 5ms/step - loss: 9.2228e-12
Epoch 3/500
1/1 [==============================] - 0s 4ms/step - loss: 8.4099e-12
Epoch 4/500
1/1 [==============================] - 0s 5ms/step - loss: 7.7207e-12
Epoch 5/500
1/1 [==============================] - 0s 7ms/step - loss: 7.2026e-12
Epoch 6/500
1/1 [==============================] - 0s 4ms/step - loss: 6.5024e-12
Epoch 7/500
1/1 [==============================] - 0s 7ms/step - loss: 5.9701e-12
Epoch 8/500
1/1 [==============================] - 0s 5ms/step - loss: 5.5341e-12
Epoch 9/500
1/1 [==============================] - 0s 6ms/step - loss: 5.0565e-12
Epoch 10/500
1/1 [==============================] - 0s 6ms/step - loss: 4.6167e-12
Epoch 11/500
1/1 [==============================] - 0s 5ms/step - loss: 4.2500e-12
Epoch 12/500
1/1 [==============================] - 0s 6ms/step - loss: 3.9617e-12
Epoch 13/500


Epoch 100/500
1/1 [==============================] - 0s 5ms/step - loss: 7.3464e-14
Epoch 101/500
1/1 [==============================] - 0s 3ms/step - loss: 6.5636e-14
Epoch 102/500
1/1 [==============================] - 0s 4ms/step - loss: 6.5617e-14
Epoch 103/500
1/1 [==============================] - 0s 4ms/step - loss: 6.5603e-14
Epoch 104/500
1/1 [==============================] - 0s 3ms/step - loss: 6.5609e-14
Epoch 105/500
1/1 [==============================] - 0s 4ms/step - loss: 6.5617e-14
Epoch 106/500
1/1 [==============================] - 0s 3ms/step - loss: 6.5617e-14
Epoch 107/500
1/1 [==============================] - 0s 5ms/step - loss: 7.0058e-14
Epoch 108/500
1/1 [==============================] - 0s 5ms/step - loss: 6.9658e-14
Epoch 109/500
1/1 [==============================] - 0s 3ms/step - loss: 6.9651e-14
Epoch 110/500
1/1 [==============================] - 0s 4ms/step - loss: 6.9644e-14
Epoch 111/500
1/1 [==============================] - 0s 4ms/step - loss: 6.9

Epoch 198/500
1/1 [==============================] - 0s 4ms/step - loss: 2.5047e-14
Epoch 199/500
1/1 [==============================] - 0s 3ms/step - loss: 2.5047e-14
Epoch 200/500
1/1 [==============================] - 0s 5ms/step - loss: 2.5047e-14
Epoch 201/500
1/1 [==============================] - 0s 3ms/step - loss: 2.7334e-14
Epoch 202/500
1/1 [==============================] - 0s 4ms/step - loss: 2.7314e-14
Epoch 203/500
1/1 [==============================] - 0s 4ms/step - loss: 2.7178e-14
Epoch 204/500
1/1 [==============================] - 0s 4ms/step - loss: 2.7248e-14
Epoch 205/500
1/1 [==============================] - 0s 5ms/step - loss: 2.7051e-14
Epoch 206/500
1/1 [==============================] - 0s 4ms/step - loss: 2.7056e-14
Epoch 207/500
1/1 [==============================] - 0s 3ms/step - loss: 2.7056e-14
Epoch 208/500
1/1 [==============================] - 0s 5ms/step - loss: 2.7056e-14
Epoch 209/500
1/1 [==============================] - 0s 4ms/step - loss: 2.7

Epoch 296/500
1/1 [==============================] - 0s 4ms/step - loss: 1.2130e-14
Epoch 297/500
1/1 [==============================] - 0s 4ms/step - loss: 1.2124e-14
Epoch 298/500
1/1 [==============================] - 0s 4ms/step - loss: 1.2324e-14
Epoch 299/500
1/1 [==============================] - 0s 3ms/step - loss: 1.2374e-14
Epoch 300/500
1/1 [==============================] - 0s 4ms/step - loss: 1.2374e-14
Epoch 301/500
1/1 [==============================] - 0s 3ms/step - loss: 1.2196e-14
Epoch 302/500
1/1 [==============================] - 0s 5ms/step - loss: 1.2082e-14
Epoch 303/500
1/1 [==============================] - 0s 4ms/step - loss: 1.2141e-14
Epoch 304/500
1/1 [==============================] - 0s 3ms/step - loss: 1.2374e-14
Epoch 305/500
1/1 [==============================] - 0s 4ms/step - loss: 1.2374e-14
Epoch 306/500
1/1 [==============================] - 0s 4ms/step - loss: 1.2180e-14
Epoch 307/500
1/1 [==============================] - 0s 3ms/step - loss: 1.2

Epoch 394/500
1/1 [==============================] - 0s 4ms/step - loss: 9.9476e-15
Epoch 395/500
1/1 [==============================] - 0s 4ms/step - loss: 9.9476e-15
Epoch 396/500
1/1 [==============================] - 0s 4ms/step - loss: 9.9476e-15
Epoch 397/500
1/1 [==============================] - 0s 4ms/step - loss: 9.9476e-15
Epoch 398/500
1/1 [==============================] - 0s 4ms/step - loss: 9.9476e-15
Epoch 399/500
1/1 [==============================] - 0s 4ms/step - loss: 9.9476e-15
Epoch 400/500
1/1 [==============================] - 0s 4ms/step - loss: 9.9476e-15
Epoch 401/500
1/1 [==============================] - 0s 4ms/step - loss: 9.9476e-15
Epoch 402/500
1/1 [==============================] - 0s 3ms/step - loss: 9.9476e-15
Epoch 403/500
1/1 [==============================] - 0s 4ms/step - loss: 1.0136e-14
Epoch 404/500
1/1 [==============================] - 0s 5ms/step - loss: 1.0136e-14
Epoch 405/500
1/1 [==============================] - 0s 3ms/step - loss: 1.0

Epoch 492/500
1/1 [==============================] - 0s 6ms/step - loss: 3.2002e-15
Epoch 493/500
1/1 [==============================] - 0s 10ms/step - loss: 3.2002e-15
Epoch 494/500
1/1 [==============================] - 0s 4ms/step - loss: 3.2002e-15
Epoch 495/500
1/1 [==============================] - 0s 5ms/step - loss: 3.2002e-15
Epoch 496/500
1/1 [==============================] - 0s 5ms/step - loss: 3.0649e-15
Epoch 497/500
1/1 [==============================] - 0s 3ms/step - loss: 3.0642e-15
Epoch 498/500
1/1 [==============================] - 0s 3ms/step - loss: 3.0649e-15
Epoch 499/500
1/1 [==============================] - 0s 4ms/step - loss: 3.0649e-15
Epoch 500/500
1/1 [==============================] - 0s 3ms/step - loss: 3.0649e-15


In [21]:
result = model.predict(X,batch_size = n_batch)

In [22]:
result

array([[-1.8626451e-09,  2.0000002e-01,  3.9999992e-01,  5.9999996e-01,
         8.0000007e-01]], dtype=float32)