In [1]:
import numpy as np

In [2]:
def split_sequences(sequences,n_steps_in,n_steps_out):
    X = list()
    Y = list()
    for i in range(len(sequences)):
        # find the end of this pattern
        end_ix = i + n_steps_in #(0+3,1+3,2+3,4+3,5+3)
        out_end_ix = end_ix + n_steps_out #(3+2,4+2,5+2,6+2,7+2)
        # check if we are beyond the dataset
        if out_end_ix > len(sequences):
            break
        # gather input and output parts of the pattern
        seq_x = sequences[i:end_ix]
        seq_y = sequences[end_ix:out_end_ix]
        X.append(seq_x)
        Y.append(seq_y)
    return np.array(X),np.array(Y)

In [3]:
# define input sequence
sequence = [10,20,30,40,50,60,70,80,90]

In [4]:
n_steps = 3
n_steps_out = 2

In [6]:
X,Y = split_sequences(sequence,n_steps,n_steps_out)

In [7]:
X

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50],
       [40, 50, 60],
       [50, 60, 70]])

In [8]:
X.shape

(5, 3)

In [9]:
Y

array([[40, 50],
       [50, 60],
       [60, 70],
       [70, 80],
       [80, 90]])

In [10]:
Y.shape

(5, 2)

In [11]:
n_features = 1

The LSTM expects data to have a three-dimensional structure of [samples, timesteps, features], and in this case,

we only have one feature so the reshape is straightforward.

In [12]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
X = X.reshape((X.shape[0],X.shape[1],n_features))

In [13]:
X.shape

(5, 3, 1)

# Model Building

In [15]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

In [45]:
model = Sequential()
model.add(LSTM(50,activation = 'relu',return_sequences = True,input_shape = (n_steps,n_features)))
model.add(LSTM(50,activation = 'relu'))
model.add(Dense(n_steps_out))
model.compile(optimizer = 'adam',loss = 'mse')

In [46]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_11 (LSTM)               (None, 3, 50)             10400     
_________________________________________________________________
lstm_12 (LSTM)               (None, 50)                20200     
_________________________________________________________________
dense_6 (Dense)              (None, 2)                 102       
Total params: 30,702
Trainable params: 30,702
Non-trainable params: 0
_________________________________________________________________


In [47]:
model.fit(X,Y,epochs = 200)

Epoch 1/200
5/5 [==============================] - 1s 295ms/step - loss: 4446.5117
Epoch 2/200
5/5 [==============================] - 0s 991us/step - loss: 4439.9551
Epoch 3/200
5/5 [==============================] - 0s 1ms/step - loss: 4433.7354
Epoch 4/200
5/5 [==============================] - 0s 1ms/step - loss: 4427.6245
Epoch 5/200
5/5 [==============================] - 0s 1ms/step - loss: 4421.4126
Epoch 6/200
5/5 [==============================] - 0s 1ms/step - loss: 4415.0283
Epoch 7/200
5/5 [==============================] - 0s 1ms/step - loss: 4408.4370
Epoch 8/200
5/5 [==============================] - 0s 999us/step - loss: 4401.4316
Epoch 9/200
5/5 [==============================] - 0s 2ms/step - loss: 4393.6543
Epoch 10/200
5/5 [==============================] - 0s 1ms/step - loss: 4385.2930
Epoch 11/200
5/5 [==============================] - 0s 2ms/step - loss: 4375.8901
Epoch 12/200
5/5 [==============================] - 0s 1ms/step - loss: 4365.4766
Epoch 13/200
5/5 [=

Epoch 102/200
5/5 [==============================] - 0s 1ms/step - loss: 0.4492
Epoch 103/200
5/5 [==============================] - 0s 997us/step - loss: 0.3083
Epoch 104/200
5/5 [==============================] - 0s 999us/step - loss: 0.2178
Epoch 105/200
5/5 [==============================] - 0s 997us/step - loss: 0.1824
Epoch 106/200
5/5 [==============================] - 0s 997us/step - loss: 0.1811
Epoch 107/200
5/5 [==============================] - 0s 1ms/step - loss: 0.1850
Epoch 108/200
5/5 [==============================] - 0s 798us/step - loss: 0.1849
Epoch 109/200
5/5 [==============================] - 0s 1ms/step - loss: 0.1821
Epoch 110/200
5/5 [==============================] - 0s 997us/step - loss: 0.1820
Epoch 111/200
5/5 [==============================] - 0s 997us/step - loss: 0.1877
Epoch 112/200
5/5 [==============================] - 0s 996us/step - loss: 0.1964
Epoch 113/200
5/5 [==============================] - 0s 997us/step - loss: 0.2059
Epoch 114/200
5/5 [===

In [48]:
x_input = np.array([70,80,90])

In [49]:
x_input.shape

(3,)

In [50]:
x_input = x_input.reshape((1,n_steps,n_features))


In [51]:
x_input.shape

(1, 3, 1)

In [52]:
model.predict(x_input)

array([[100.25543, 109.41533]], dtype=float32)