In [1]:
import numpy as np

In [56]:
# split a univariate sequence into samples
def split_sequence(sequence,n_steps):
    X = list()
    Y = list()
    for i in range(len(sequence)):#0-8
        # find the end of this pattern
        end_ix = i + n_steps#i+3(3,4,5,6,7,8,9,10,11)
        # check if we are beyond the sequence
        if end_ix > len(sequence): #end_ix[3,4,5,6,7,8,9] > 9
            break
        seq_x = sequence[i:end_ix,:-1]#
        seq_y = sequence[end_ix-1,-1]#
        X.append(seq_x)
        Y.append(seq_y)
    return np.array(X),np.array(Y)

In [57]:
#input sequences
seq1 = np.array([10,20,30,40,50,60,70,80,90])
seq2 = np.array([15,25,35,45,55,65,75,85,95])

In [58]:
print(seq1.shape)
print(seq2.shape)

(9,)
(9,)


In [59]:
#output sequence
out_seq = np.array([seq1[i]+seq2[i] for i in range(len(seq1)) ])

In [60]:
out_seq

array([ 25,  45,  65,  85, 105, 125, 145, 165, 185])

In [61]:
# convert to [rows, columns] structure

In [62]:
seq1 = seq1.reshape(len(seq1),1)
seq2 = seq2.reshape(len(seq2),1)
out_seq = out_seq.reshape(len(out_seq ),1)

In [63]:
print(seq1.shape)
print(seq2.shape)
print(out_seq.shape)


(9, 1)
(9, 1)
(9, 1)


In [64]:
dataset = np.hstack((seq1,seq2,out_seq))

In [65]:
dataset

array([[ 10,  15,  25],
       [ 20,  25,  45],
       [ 30,  35,  65],
       [ 40,  45,  85],
       [ 50,  55, 105],
       [ 60,  65, 125],
       [ 70,  75, 145],
       [ 80,  85, 165],
       [ 90,  95, 185]])

In [66]:
dataset.shape

(9, 3)

In [67]:
# choose a number of time steps
n_steps = 3

In [68]:
X,Y = split_sequence(dataset,n_steps)

In [69]:
X

array([[[10, 15],
        [20, 25],
        [30, 35]],

       [[20, 25],
        [30, 35],
        [40, 45]],

       [[30, 35],
        [40, 45],
        [50, 55]],

       [[40, 45],
        [50, 55],
        [60, 65]],

       [[50, 55],
        [60, 65],
        [70, 75]],

       [[60, 65],
        [70, 75],
        [80, 85]],

       [[70, 75],
        [80, 85],
        [90, 95]]])

In [70]:
Y

array([ 65,  85, 105, 125, 145, 165, 185])

In [73]:
X.shape

(7, 3, 2)

The first dimension is the number of samples, in this case 7. 

The second dimension is the number of time steps per sample, in this case 3, the value specified to the function.

Finally, the last dimension specifies the number of parallel time series or the number of variables,

in this case 2 for the two parallel series

In [75]:
Y.shape

(7,)

In [77]:
for i in range(len(X)):
    print(X[i], Y[i])

[[10 15]
 [20 25]
 [30 35]] 65
[[20 25]
 [30 35]
 [40 45]] 85
[[30 35]
 [40 45]
 [50 55]] 105
[[40 45]
 [50 55]
 [60 65]] 125
[[50 55]
 [60 65]
 [70 75]] 145
[[60 65]
 [70 75]
 [80 85]] 165
[[70 75]
 [80 85]
 [90 95]] 185


# Model Building

In [79]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [80]:
# the dataset knows the number of features, e.g. 2
n_features = X.shape[2]

In [82]:
model = Sequential()
model.add(LSTM(50,activation = 'relu',input_shape = (n_steps,n_features)))
model.add(Dense(1))
model.compile(optimizer = 'adam',loss = 'mean_squared_error')

In [83]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 50)                10600     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 51        
Total params: 10,651
Trainable params: 10,651
Non-trainable params: 0
_________________________________________________________________


In [85]:
model.fit(X,Y,epochs = 200,verbose = 2)

Epoch 1/200
 - 0s - loss: 0.0557
Epoch 2/200
 - 0s - loss: 0.0548
Epoch 3/200
 - 0s - loss: 0.0539
Epoch 4/200
 - 0s - loss: 0.0531
Epoch 5/200
 - 0s - loss: 0.0524
Epoch 6/200
 - 0s - loss: 0.0517
Epoch 7/200
 - 0s - loss: 0.0510
Epoch 8/200
 - 0s - loss: 0.0504
Epoch 9/200
 - 0s - loss: 0.0499
Epoch 10/200
 - 0s - loss: 0.0493
Epoch 11/200
 - 0s - loss: 0.0488
Epoch 12/200
 - 0s - loss: 0.0483
Epoch 13/200
 - 0s - loss: 0.0478
Epoch 14/200
 - 0s - loss: 0.0474
Epoch 15/200
 - 0s - loss: 0.0469
Epoch 16/200
 - 0s - loss: 0.0465
Epoch 17/200
 - 0s - loss: 0.0460
Epoch 18/200
 - 0s - loss: 0.0456
Epoch 19/200
 - 0s - loss: 0.0451
Epoch 20/200
 - 0s - loss: 0.0446
Epoch 21/200
 - 0s - loss: 0.0442
Epoch 22/200
 - 0s - loss: 0.0437
Epoch 23/200
 - 0s - loss: 0.0433
Epoch 24/200
 - 0s - loss: 0.0428
Epoch 25/200
 - 0s - loss: 0.0423
Epoch 26/200
 - 0s - loss: 0.0419
Epoch 27/200
 - 0s - loss: 0.0414
Epoch 28/200
 - 0s - loss: 0.0409
Epoch 29/200
 - 0s - loss: 0.0405
Epoch 30/200
 - 0s - lo

In [87]:
x_input = np.array([[80,85],[90,95],[100,105]])

The shape of the one sample with three time steps and two variables must be [1, 3, 2].

In [89]:
x_input = x_input.reshape((1,n_steps,n_features))

In [90]:
x_input.shape

(1, 3, 2)

When making a prediction, the model expects three time steps for two input time series.

In [91]:
model.predict(x_input)

array([[207.29121]], dtype=float32)