In [1]:
from random import random
from numpy import array
from numpy import cumsum

In [2]:
#cumsum (pos1, pos1+pos2, pos1+pos2+pos3, ...)

In [3]:
def get_sequence(n_timesteps):
    # create a sequence of random numbers in [0,1]
    X = array([random() for _ in range(n_timesteps)])
    # calculate cut-off value to change class(output) values
    limit = 10/4.0
    # determine the class outcome for each item in cumulative sequence
    y = array([0 if x < limit else 1 for x in cumsum(X)])
    
    # reshape input and output data to be suitable for LSTMs
    X = X.reshape(1, n_timesteps, 1)#(samples,timesteps,features)
    y = y.reshape(1, n_timesteps, 1)

    return X,y


In [4]:
n_timesteps = 10

In [6]:
get_sequence(n_timesteps)

(array([[[0.61362692],
         [0.63868121],
         [0.01322661],
         [0.54294111],
         [0.66596469],
         [0.58707537],
         [0.80729566],
         [0.80151401],
         [0.8823208 ],
         [0.51061944]]]),
 array([[[0],
         [0],
         [0],
         [0],
         [0],
         [1],
         [1],
         [1],
         [1],
         [1]]]))

In [7]:
X,y = get_sequence(10)
print(X)
print(y)

[[[0.77617563]
  [0.47655313]
  [0.39779102]
  [0.19349229]
  [0.10121961]
  [0.42042607]
  [0.00322307]
  [0.28785665]
  [0.60671002]
  [0.90196588]]]
[[[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [1]
  [1]
  [1]]]


In [8]:
for x in cumsum(X):
    print(x)

0.7761756267360084
1.252728753229941
1.6505197747107794
1.844012068602611
1.9452316802908056
2.365657751771428
2.36888082461774
2.656737479564113
3.263447495973385
4.165413377772029


# A TimeDistributed wrapper layer is used around the output layer so that one value per timestep can be predicted given the full sequence provided as input. This requires that the LSTM hidden layer returns a sequence of values (one per timestep) rather than a single value for the whole input sequence.

In [10]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import TimeDistributed

In [12]:
model = Sequential()
model.add(LSTM(20,input_shape = (n_timesteps,1),return_sequences = True))
model.add(TimeDistributed(Dense(1,activation = 'sigmoid')))

In [14]:
model.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

# The LSTM will be trained for 1,000 epochs. A new random input sequence will be generated each epoch for the network to be fit on. This ensures that the model does not memorize a single sequence and instead can generalize a solution to solve all possible random input sequences for this problem.

In [17]:
for epoch in range(1000):
    # generate new random sequence for every iteration
    X,y = get_sequence(n_timesteps)
    #fit the model
    model.fit(X,y,epochs = 1,batch_size = 1)

Epoch 1/1
1/1 [==============================] - 0s 9ms/step - loss: 0.1079 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.1280 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.1711 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.2384 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 8ms/step - loss: 0.3351 - acc: 0.8000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.3247 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 9ms/step - loss: 0.1889 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.1789 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 9ms/step - loss: 0.1127 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 9ms/step - loss: 0.1508 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.1063 - acc: 1.0000
Epoch 1/1


1/1 [==============================] - 0s 6ms/step - loss: 0.1621 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.3524 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.2129 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.0939 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.0933 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.0891 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.1207 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.0907 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1231 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.0977 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 8ms/step - loss: 0.1576 - acc: 0.9000
Epoch 1/1
1/1 [=====

Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1889 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.1240 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1475 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.1879 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 8ms/step - loss: 0.1256 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1496 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.2823 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.1153 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.2549 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.1079 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.2608 - acc: 0.9000
Epoch 1/1


Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1312 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1571 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1624 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.3929 - acc: 0.8000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.2381 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 4ms/step - loss: 0.0750 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.3827 - acc: 0.8000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.4252 - acc: 0.8000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.0831 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.0915 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1096 - acc: 1.0000
Epoch 1/1


Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.1783 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.0949 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.2968 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1869 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.1570 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.2342 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.1573 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.1252 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.2327 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.1798 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.0786 - acc: 1.0000
Epoch 1/1


1/1 [==============================] - 0s 8ms/step - loss: 0.1498 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.0938 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 8ms/step - loss: 0.1078 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 8ms/step - loss: 0.0964 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 8ms/step - loss: 0.1217 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 8ms/step - loss: 0.2660 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.1050 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 9ms/step - loss: 0.1260 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 8ms/step - loss: 0.1788 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.0860 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 8ms/step - loss: 0.1044 - acc: 1.0000
Epoch 1/1
1/1 [=====

Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.1622 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.2256 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1582 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1065 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1529 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1078 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.2780 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.0851 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.2257 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.1275 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 8ms/step - loss: 0.0741 - acc: 1.0000
Epoch 1/1


1/1 [==============================] - 0s 6ms/step - loss: 0.2359 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1090 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1957 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 8ms/step - loss: 0.1303 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1084 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1370 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1511 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.1015 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.1172 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.1351 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.1574 - acc: 0.9000
Epoch 1/1
1/1 [=====

Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.0782 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.1767 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.0865 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1518 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.0462 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.0577 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.0947 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.2196 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.2092 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.4784 - acc: 0.8000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.0821 - acc: 1.0000
Epoch 1/1


1/1 [==============================] - 0s 6ms/step - loss: 0.1262 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 8ms/step - loss: 0.0481 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.1188 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 9ms/step - loss: 0.0691 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.0603 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.0932 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1139 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1006 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.0906 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1669 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.1099 - acc: 1.0000
Epoch 1/1
1/1 [=====

Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.0868 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.0395 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1286 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 8ms/step - loss: 0.2481 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.1298 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1072 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.3534 - acc: 0.8000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.1126 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 6ms/step - loss: 0.1346 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 5ms/step - loss: 0.1510 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 7ms/step - loss: 0.0843 - acc: 1.0000
Epoch 1/1


In [21]:
# evaluate LSTM
X,y = get_sequence(n_timesteps)
print(X)
print(y)


[[[0.67857824]
  [0.05221406]
  [0.75248398]
  [0.54614406]
  [0.19939563]
  [0.61058228]
  [0.13760771]
  [0.68379131]
  [0.77915194]
  [0.27905677]]]
[[[0]
  [0]
  [0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]
  [1]]]


In [24]:
for x in cumsum(X):
    print(x)

0.6785782383529236
0.7307922962245196
1.483276274761615
2.0294203370993973
2.228815966488985
2.839398248006124
2.9770059604592727
3.6607972725424696
4.439949215050415
4.719005983379446


In [22]:
yhat = model.predict_classes(X)

In [23]:
yhat

array([[[0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1]]])

In [29]:
for i in range(n_timesteps):
    print("Actual : ", y[0,i],'Predicted : ', yhat[0,i],)

Actual :  [0] Predicted :  [0]
Actual :  [0] Predicted :  [0]
Actual :  [0] Predicted :  [0]
Actual :  [0] Predicted :  [0]
Actual :  [0] Predicted :  [1]
Actual :  [1] Predicted :  [1]
Actual :  [1] Predicted :  [1]
Actual :  [1] Predicted :  [1]
Actual :  [1] Predicted :  [1]
Actual :  [1] Predicted :  [1]
