In [1]:
from random import random
from numpy import array
from numpy import cumsum

In [2]:
#cumsum (pos1, pos1+pos2, pos1+pos2+pos3, ...)

In [3]:
def get_sequence(n_timesteps):
    # create a sequence of random numbers in [0,1]
    X = array([random() for _ in range(n_timesteps)])
    # calculate cut-off value to change class(output) values
    limit = 10/4.0
    # determine the class outcome for each item in cumulative sequence
    y = array([0 if x < limit else 1 for x in cumsum(X)])
    
    # reshape input and output data to be suitable for LSTMs
    X = X.reshape(1, n_timesteps, 1)#(samples,timesteps,features)
    y = y.reshape(1, n_timesteps, 1)

    return X,y


In [4]:
n_timesteps = 10

In [5]:
get_sequence(n_timesteps)

(array([[[0.89351233],
         [0.65828704],
         [0.09161519],
         [0.08018807],
         [0.83473628],
         [0.46653784],
         [0.61361792],
         [0.95748196],
         [0.72837314],
         [0.30109043]]]),
 array([[[0],
         [0],
         [0],
         [0],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1]]]))

In [6]:
X,y = get_sequence(10)
print(X)
print(y)

[[[0.19042246]
  [0.82980477]
  [0.60616355]
  [0.13771802]
  [0.40106313]
  [0.61043055]
  [0.87846221]
  [0.22955336]
  [0.58156358]
  [0.66530663]]]
[[[0]
  [0]
  [0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]
  [1]]]


In [7]:
for x in cumsum(X):
    print(x)

0.19042246152101838
1.0202272330244337
1.6263907876936532
1.764108811905397
2.1651719408749397
2.7756024920074536
3.6540647034071307
3.883618066512289
4.4651816416267085
5.130488272493073


In [9]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Bidirectional
from keras.layers import Dense
from keras.layers import TimeDistributed

In [11]:
model = Sequential()
model.add(Bidirectional(LSTM(20,input_shape = (n_timesteps,1),return_sequences = True)))
model.add(TimeDistributed(Dense(1,activation = 'sigmoid')))

In [13]:
model.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [15]:
for epoch in range(1000):
    # generate new random sequence for every iteration
    X,y = get_sequence(n_timesteps)
    #fit the model
    model.fit(X,y,epochs = 1,batch_size = 1)

Epoch 1/1
1/1 [==============================] - 0s 14ms/step - loss: 0.0977 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 13ms/step - loss: 0.1087 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 11ms/step - loss: 0.1894 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 11ms/step - loss: 0.2294 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 10ms/step - loss: 0.1498 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 9ms/step - loss: 0.1118 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 10ms/step - loss: 0.0729 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 10ms/step - loss: 0.0841 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 11ms/step - loss: 0.0854 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 10ms/step - loss: 0.0680 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 10ms/step - loss: 0.2709 - acc: 0.9000


Epoch 1/1
1/1 [==============================] - 0s 10ms/step - loss: 0.0669 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 10ms/step - loss: 0.7904 - acc: 0.7000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.0652 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.1159 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 14ms/step - loss: 0.1401 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.1942 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 19ms/step - loss: 0.1206 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 16ms/step - loss: 0.1345 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 14ms/step - loss: 0.2003 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 13ms/step - loss: 0.1883 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 13ms/step - loss: 0.0910 - acc: 1.0000

1/1 [==============================] - 0s 12ms/step - loss: 0.0713 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 12ms/step - loss: 0.1034 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 9ms/step - loss: 0.0907 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.0873 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 17ms/step - loss: 0.1299 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 16ms/step - loss: 0.0885 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 14ms/step - loss: 0.0908 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 18ms/step - loss: 0.0820 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 17ms/step - loss: 0.3076 - acc: 0.8000
Epoch 1/1
1/1 [==============================] - 0s 17ms/step - loss: 0.0848 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 18ms/step - loss: 0.1434 - acc: 0.9000
Epoch 1/1


Epoch 1/1
1/1 [==============================] - 0s 13ms/step - loss: 0.0925 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 14ms/step - loss: 0.1548 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 11ms/step - loss: 0.0528 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 11ms/step - loss: 0.0530 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 12ms/step - loss: 0.3881 - acc: 0.8000
Epoch 1/1
1/1 [==============================] - 0s 13ms/step - loss: 0.0526 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.1829 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 14ms/step - loss: 0.0774 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 12ms/step - loss: 0.2318 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 13ms/step - loss: 0.0550 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 11ms/step - loss: 0.1296 - acc: 0.9000

1/1 [==============================] - 0s 15ms/step - loss: 0.0533 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.0533 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.1057 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.2061 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.0996 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 16ms/step - loss: 0.0763 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 16ms/step - loss: 0.5968 - acc: 0.7000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.0738 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 16ms/step - loss: 0.0839 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.2284 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 16ms/step - loss: 0.0996 - acc: 0.9000
Epoch 1/1

Epoch 1/1
1/1 [==============================] - 0s 14ms/step - loss: 0.0504 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 11ms/step - loss: 0.1163 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 12ms/step - loss: 0.1847 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 13ms/step - loss: 0.0856 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 13ms/step - loss: 0.0725 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 13ms/step - loss: 0.1689 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 11ms/step - loss: 0.0561 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 12ms/step - loss: 0.0697 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 11ms/step - loss: 0.1581 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 12ms/step - loss: 0.0757 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 10ms/step - loss: 0.0590 - acc: 1.0000

1/1 [==============================] - 0s 10ms/step - loss: 0.0598 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 9ms/step - loss: 0.0854 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 11ms/step - loss: 0.0463 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 13ms/step - loss: 0.3708 - acc: 0.8000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.0874 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.0950 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.0618 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 16ms/step - loss: 0.2056 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.0888 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.0839 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 16ms/step - loss: 0.0445 - acc: 1.0000
Epoch 1/1


Epoch 1/1
1/1 [==============================] - 0s 13ms/step - loss: 0.1869 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.0414 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.0538 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.1611 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.0794 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 14ms/step - loss: 0.1165 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 14ms/step - loss: 0.1220 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 16ms/step - loss: 0.1691 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 16ms/step - loss: 0.2047 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.1069 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 13ms/step - loss: 0.0815 - acc: 1.0000

Epoch 1/1
1/1 [==============================] - 0s 10ms/step - loss: 0.0491 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 11ms/step - loss: 0.0624 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 10ms/step - loss: 0.0869 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 11ms/step - loss: 0.0545 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 11ms/step - loss: 0.0884 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 14ms/step - loss: 0.2228 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 16ms/step - loss: 0.0576 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 14ms/step - loss: 0.0694 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 12ms/step - loss: 0.0951 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 13ms/step - loss: 0.0721 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 11ms/step - loss: 0.0876 - acc: 0.9000

1/1 [==============================] - 0s 14ms/step - loss: 0.0466 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 12ms/step - loss: 0.1423 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 12ms/step - loss: 0.2011 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 13ms/step - loss: 0.6214 - acc: 0.6000
Epoch 1/1
1/1 [==============================] - 0s 17ms/step - loss: 0.1030 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 17ms/step - loss: 0.0526 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 13ms/step - loss: 0.0402 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.0702 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 17ms/step - loss: 0.0472 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 14ms/step - loss: 0.1197 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 14ms/step - loss: 0.2040 - acc: 0.9000
Epoch 1/1

Epoch 1/1
1/1 [==============================] - 0s 9ms/step - loss: 0.0530 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 8ms/step - loss: 0.0623 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 10ms/step - loss: 0.0524 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 11ms/step - loss: 0.0328 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 12ms/step - loss: 0.0990 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 10ms/step - loss: 0.0977 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 14ms/step - loss: 0.1867 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 13ms/step - loss: 0.0606 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 9ms/step - loss: 0.0885 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 9ms/step - loss: 0.0411 - acc: 1.0000
Epoch 1/1
1/1 [==============================] - 0s 9ms/step - loss: 0.1103 - acc: 0.9000
Epoc

Epoch 1/1
1/1 [==============================] - 0s 14ms/step - loss: 0.1040 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 17ms/step - loss: 0.1872 - acc: 0.9000
Epoch 1/1
1/1 [==============================] - 0s 15ms/step - loss: 0.0744 - acc: 1.0000


In [16]:
# evaluate LSTM
X,y = get_sequence(n_timesteps)
print(X)
print(y)


[[[0.78498956]
  [0.90181922]
  [0.10069017]
  [0.16684916]
  [0.62677174]
  [0.45597727]
  [0.96772496]
  [0.79392183]
  [0.60109631]
  [0.91410931]]]
[[[0]
  [0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [1]
  [1]
  [1]]]


In [17]:
for x in cumsum(X):
    print(x)

0.7849895634147315
1.6868087859595502
1.7874989577772489
1.9543481160368326
2.581119859482684
3.0370971277915295
4.004822092320364
4.7987439194863954
5.399840229452763
6.313949540678329


In [18]:
yhat = model.predict_classes(X)

In [19]:
yhat

array([[[0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1]]])

In [20]:
for i in range(n_timesteps):
    print("Actual : ", y[0,i],'Predicted : ', yhat[0,i],)

Actual :  [0] Predicted :  [0]
Actual :  [0] Predicted :  [0]
Actual :  [0] Predicted :  [0]
Actual :  [0] Predicted :  [0]
Actual :  [1] Predicted :  [1]
Actual :  [1] Predicted :  [1]
Actual :  [1] Predicted :  [1]
Actual :  [1] Predicted :  [1]
Actual :  [1] Predicted :  [1]
Actual :  [1] Predicted :  [1]
