In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("C:/Users/TANNERU/Downloads/Dataset for coding/SMSSpamCollection",sep = '\t',names = ['label','message'])

In [4]:
df

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
X = df['message']
Y = df['label']

In [6]:
X

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: message, Length: 5572, dtype: object

In [7]:
Y

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: label, Length: 5572, dtype: object

In [8]:
from collections import Counter
print(Counter(Y))

Counter({'ham': 4825, 'spam': 747})


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [10]:
Y

array([0, 0, 1, ..., 0, 0, 0])

In [11]:
from collections import Counter
print(Counter(Y))

Counter({0: 4825, 1: 747})


In [12]:
X[5569]

'Pity, * was in mood for that. So...any other suggestions?'

# Data Cleaning

In [13]:
import re
import nltk
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [14]:
ps = PorterStemmer()
lemma = WordNetLemmatizer()
corpus = []

In [15]:
for i in range(0,len(X)):
    review = re.sub('[^a-zA-Z]',' ',X[i])
    review = review.lower()
    review = review.split()
    #stemming
    #review = [ps.stem(word) for word in review if word not in stopwords.words('english')]
    #lemmatising
    review = [lemma.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)
    

In [16]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [17]:
len(corpus)

5572

In [19]:
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import GRU
from keras.layers import Dropout
from keras.layers.embeddings import Embedding

# ONEHOT

In [20]:
vocab_size = 5000

In [21]:
onehot = [one_hot(word,vocab_size) for word in corpus]

In [22]:
onehot

[[1906,
  189,
  296,
  1991,
  2002,
  1092,
  4948,
  3788,
  4471,
  1050,
  272,
  280,
  2743,
  4000,
  2157,
  2180],
 [2925, 792, 3099, 4443, 1502, 666],
 [4322,
  1973,
  2823,
  3534,
  3803,
  358,
  4599,
  2188,
  4990,
  1888,
  4949,
  2109,
  358,
  2975,
  1973,
  7,
  2564,
  3954,
  810,
  3922,
  3895],
 [1502, 2193, 920, 2486, 2380, 1502, 3922, 3830, 920],
 [2532, 3358, 1906, 2006, 1159, 1570, 4280],
 [3474,
  2926,
  4455,
  2549,
  1419,
  3634,
  1868,
  112,
  2292,
  890,
  2925,
  1847,
  2564,
  3481,
  4180,
  924],
 [1407, 992, 1868, 4698, 3960, 1868, 3314, 2942],
 [1344,
  473,
  3286,
  3286,
  1943,
  1777,
  4561,
  3405,
  4528,
  423,
  1745,
  4775,
  702,
  4530,
  423],
 [3747,
  4198,
  4803,
  23,
  931,
  4617,
  2239,
  1757,
  1390,
  775,
  1390,
  3510,
  1036,
  2804,
  2787],
 [3451,
  2488,
  1502,
  1264,
  245,
  3063,
  283,
  3668,
  3451,
  4680,
  4322,
  775,
  3451,
  3063,
  3185,
  4322],
 [4629, 2715, 1997, 884, 126, 1858, 177

In [23]:
onehot[199]

[2827, 4773, 1407, 2224, 418, 789, 1072, 4630, 4999, 3954, 3634, 1502, 1847]

In [25]:
len(onehot[199])

13

# Padding

In [26]:
max_length = 25

In [27]:
pad_docs = pad_sequences(onehot,padding ='pre',maxlen = max_length)

In [28]:
pad_docs

array([[   0,    0,    0, ..., 4000, 2157, 2180],
       [   0,    0,    0, ..., 4443, 1502,  666],
       [   0,    0,    0, ...,  810, 3922, 3895],
       ...,
       [   0,    0,    0, ..., 2178, 3121, 1497],
       [   0,    0,    0, ..., 4754, 1502, 4322],
       [   0,    0,    0, ..., 1896, 1499,  905]])

In [29]:
pad_docs.shape

(5572, 25)

# Building Model

In [30]:
dimensions = 40

In [32]:
model = Sequential()
#Embedding Layer
model.add(Embedding(vocab_size,dimensions,input_length = max_length))
model.add(Dropout(0.3))
#add 1st GRU layer
model.add(GRU(100,activation="tanh",return_sequences=True))
model.add(Dropout(0.3))
#add 2ND GRU layer
model.add(GRU(100,activation="tanh",return_sequences=True))
model.add(Dropout(0.3))
#add 3rd GRU layer
model.add(GRU(100,activation="tanh",return_sequences=False))
model.add(Dropout(0.3))
model.add(Dense(1,activation = 'sigmoid'))
model.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [33]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 25, 40)            200000    
_________________________________________________________________
dropout_5 (Dropout)          (None, 25, 40)            0         
_________________________________________________________________
gru_4 (GRU)                  (None, 25, 100)           42300     
_________________________________________________________________
dropout_6 (Dropout)          (None, 25, 100)           0         
_________________________________________________________________
gru_5 (GRU)                  (None, 25, 100)           60300     
_________________________________________________________________
dropout_7 (Dropout)          (None, 25, 100)           0         
_________________________________________________________________
gru_6 (GRU)                  (None, 100)              

In [34]:
inputs = np.array(pad_docs)
Y = np.array(Y)#labels

In [36]:
inputs.shape,Y.shape

((5572, 25), (5572,))

# Splitting

In [37]:
from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest = train_test_split(inputs,Y,test_size = 0.25,random_state = 0) 

In [38]:
print(Xtrain.shape)
print(Xtest.shape)
print(Ytrain.shape)
print(Ytest.shape)

(4179, 25)
(1393, 25)
(4179,)
(1393,)


In [39]:
cl = model.fit(Xtrain,Ytrain,validation_data=(Xtest,Ytest),epochs=10,batch_size = 64)

Train on 4179 samples, validate on 1393 samples
Epoch 1/10
4179/4179 [==============================] - 11s 3ms/step - loss: 0.2282 - acc: 0.9198 - val_loss: 0.0605 - val_acc: 0.9821
Epoch 2/10
4179/4179 [==============================] - 7s 2ms/step - loss: 0.0435 - acc: 0.9866 - val_loss: 0.0454 - val_acc: 0.98711s - loss: 0.04
Epoch 3/10
4179/4179 [==============================] - 7s 2ms/step - loss: 0.0212 - acc: 0.9943 - val_loss: 0.0554 - val_acc: 0.9878
Epoch 4/10
4179/4179 [==============================] - 7s 2ms/step - loss: 0.0127 - acc: 0.9971 - val_loss: 0.0548 - val_acc: 0.9885
Epoch 5/10
4179/4179 [==============================] - 6s 2ms/step - loss: 0.0075 - acc: 0.9978 - val_loss: 0.0694 - val_acc: 0.9871
Epoch 6/10
4179/4179 [==============================] - 7s 2ms/step - loss: 0.0057 - acc: 0.9988 - val_loss: 0.0703 - val_acc: 0.9878
Epoch 7/10
4179/4179 [==============================] - 7s 2ms/step - loss: 0.0050 - acc: 0.9981 - val_loss: 0.0803 - val_acc: 0.984

In [40]:
Ypred = model.predict_classes(Xtest)

In [41]:
Ypred

array([[0],
       [1],
       [1],
       ...,
       [1],
       [0],
       [0]])

In [42]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Ytest,Ypred))

[[1204    4]
 [  20  165]]
